### ISSUE TITLE
`res.set()` aliases

### ISSUE THREAD

**Issue by ajuhos** [ellipse-js/ellipse#1]
`res.header()`, `res.setHeader()` aliases are missing.

**Comment by yetzt** [comment]
why isn't this in the release yet? 

i'm forced to do a workaround
``` javascript
app.use(function(req,res,next){ res.header = res.set; next(); });
```
to get various middleware working.

**Comment by schwarzkopfb** [comment]
@yetzt What release line are you referring to? Did you read this section: https://github.com/ellipse-js/ellipse#installation ?

**Comment by yetzt** [comment]
@schwarzkopfb the [npm package ellipse@0.5.5](https://www.npmjs.com/package/ellipse) installed via `npm isntall ellipse`, which was last updated two years ago.
